export const board = [
    { id: 0, name: "START", type: "start" },
    { id: 1, name: "Tatooine Homestead", type: "location", colorGroup: "brown", price: 60, rent: [2, 10, 30, 90, 160, 250], houseCost: 50, owner: null, houses: 0, mortgaged: false },
    { id: 2, name: "Supply Drop", type: "supply_drop" },
    { id: 3, name: "Jawa Sandcrawler", type: "location", colorGroup: "brown", price: 60, rent: [4, 20, 60, 180, 320, 450], houseCost: 50, owner: null, houses: 0, mortgaged: false },
    { id: 4, name: "Imperial Tax", type: "tax", amount: 200 },
    { id: 5, name: "Hyperspace Lane 1", type: "hyperspace_lane", price: 200, rent: [25,50,100,200], owner: null, mortgaged: false },
    { id: 6, name: "Mos Eisley Cantina", type: "location", colorGroup: "light-blue", price: 100, rent: [6, 30, 90, 270, 400, 550], houseCost: 50, owner: null, houses: 0, mortgaged: false },
    { id: 7, name: "Force Card", type: "force_card" },
    { id: 8, name: "Dex's Diner", type: "location", colorGroup: "light-blue", price: 100, rent: [6, 30, 90, 270, 400, 550], houseCost: 50, owner: null, houses: 0, mortgaged: false },
    { id: 9, name: "Otoh Gunga", type: "location", colorGroup: "light-blue", price: 120, rent: [8, 40, 100, 300, 450, 600], houseCost: 50, owner: null, houses: 0, mortgaged: false },
    { id: 10, name: "Detention Block / Just Visiting", type: "detention_block" },
    { id: 11, name: "Cloud City", type: "location", colorGroup: "pink", price: 140, rent: [10, 50, 150, 450, 625, 750], houseCost: 100, owner: null, houses: 0, mortgaged: false },
    { id: 12, name: "Power Generator", type: "facility", price: 150, owner: null, mortgaged: false },
    { id: 13, name: "Bespin Platforms", type: "location", colorGroup: "pink", price: 140, rent: [10, 50, 150, 450, 625, 750], houseCost: 100, owner: null, houses: 0, mortgaged: false },
    { id: 14, name: "Carbon-Freezing Chamber", type: "location", colorGroup: "pink", price: 160, rent: [12, 60, 180, 500, 700, 800], houseCost: 100, owner: null, houses: 0, mortgaged: false },
    { id: 15, name: "Hyperspace Lane 2", type: "hyperspace_lane", price: 200, rent: [25,50,100,200], owner: null, mortgaged: false },
    { id: 16, name: "Dagobah Swamp", type: "location", colorGroup: "orange", price: 180, rent: [14, 70, 200, 550, 750, 950], houseCost: 100, owner: null, houses: 0, mortgaged: false },
    { id: 17, name: "Supply Drop", type: "supply_drop" },
    { id: 18, name: "Yoda's Hut", type: "location", colorGroup: "orange", price: 180, rent: [14, 70, 200, 550, 750, 950], houseCost: 100, owner: null, houses: 0, mortgaged: false },
    { id: 19, name: "Jedi Temple", type: "location", colorGroup: "orange", price: 200, rent: [16, 80, 220, 600, 800, 1000], houseCost: 100, owner: null, houses: 0, mortgaged: false },
    { id: 20, name: "Smuggler's Hideout", type: "smugglers_hideout" },
    { id: 21, name: "Mustafar Volcano", type: "location", colorGroup: "red", price: 220, rent: [18, 90, 250, 700, 875, 1050], houseCost: 150, owner: null, houses: 0, mortgaged: false },
    { id: 22, name: "Force Card", type: "force_card" },
    { id: 23, name: "Death Star Core", type: "location", colorGroup: "red", price: 220, rent: [18, 90, 250, 700, 875, 1050], houseCost: 150, owner: null, houses: 0, mortgaged: false },
    { id: 24, name: "Starkiller Base", type: "location", colorGroup: "red", price: 240, rent: [20, 100, 300, 750, 925, 1100], houseCost: 150, owner: null, houses: 0, mortgaged: false },
    { id: 25, name: "Hyperspace Lane 3", type: "hyperspace_lane", price: 200, rent: [25,50,100,200], owner: null, mortgaged: false },
    { id: 26, name: "Coruscant Underworld", type: "location", colorGroup: "yellow", price: 260, rent: [22, 110, 330, 800, 975, 1150], houseCost: 150, owner: null, houses: 0, mortgaged: false },
    { id: 27, name: "Galactic Senate Building", type: "location", colorGroup: "yellow", price: 260, rent: [22, 110, 330, 800, 975, 1150], houseCost: 150, owner: null, houses: 0, mortgaged: false },
    { id: 28, name: "Hydroponics Farm", type: "facility", price: 150, owner: null, mortgaged: false },
    { id: 29, name: "Imperial Palace", type: "location", colorGroup: "yellow", price: 280, rent: [24, 120, 360, 850, 1025, 1200], houseCost: 150, owner: null, houses: 0, mortgaged: false },
    { id: 30, name: "Send to Detention Block", type: "send_to_detention" },
    { id: 31, name: "Endor Forest", type: "location", colorGroup: "green", price: 300, rent: [26, 130, 390, 900, 1100, 1275], houseCost: 200, owner: null, houses: 0, mortgaged: false },
    { id: 32, name: "Ewok Village", type: "location", colorGroup: "green", price: 300, rent: [26, 130, 390, 900, 1100, 1275], houseCost: 200, owner: null, houses: 0, mortgaged: false },
    { id: 33, name: "Supply Drop", type: "supply_drop" },
    { id: 34, name: "Falcon's Hangar", type: "location", colorGroup: "green", price: 320, rent: [28, 150, 450, 1000, 1200, 1400], houseCost: 200, owner: null, houses: 0, mortgaged: false },
    { id: 35, name: "Hyperspace Lane 4", type: "hyperspace_lane", price: 200, rent: [25,50,100,200], owner: null, mortgaged: false },
    { id: 36, name: "Force Card", type: "force_card" },
    { id: 37, name: "Alderaan Citadel", type: "location", colorGroup: "dark-blue", price: 350, rent: [35, 175, 500, 1100, 1300, 1500], houseCost: 200, owner: null, houses: 0, mortgaged: false },
    { id: 38, name: "Republic Tax", type: "tax", amount: 100 },
    { id: 39, name: "Death Star Throne Room", type: "location", colorGroup: "dark-blue", price: 400, rent: [50, 200, 600, 1400, 1700, 2000], houseCost: 200, owner: null, houses: 0, mortgaged: false }
];

export const chanceCards = [
    "Advance to START (Collect ₡200)",
    "Advance to Starkiller Base. If you pass START, collect ₡200.",
    "Advance to Cloud City. If you pass START, collect ₡200.",
    "Advance to nearest Facility. If unowned, you may buy it from the Bank. If owned, pay owner 10 times amount shown on dice.",
    "Advance to nearest Hyperspace Lane. If unowned, you may buy it from the Bank. If owned, pay owner twice the rental to which he/she is otherwise entitled.",
    "Bank pays you dividend of ₡50",
    "Get Out of Detention Free Card",
    "Go back 3 spaces",
    "Go to Detention Block – Go directly to Detention Block – Do not pass START, do not collect ₡200",
    "Make general repairs on all your holdings. For each Dwelling pay ₡25. For each Fortress pay ₡100.",
    "Pay poor tax of ₡15",
    "Take a trip to Hyperspace Lane 1. If you pass START, collect ₡200.",
    "Advance to Death Star Throne Room.",
    "You have been elected Chairman of the Galactic Senate – Pay each player ₡50.",
    "Your loan matures. Collect ₡150",
    "You have won a droid race competition. Collect ₡100"
];

export const communityChestCards = [
    "Advance to START (Collect ₡200)",
    "Bank error in your favor – Collect ₡200",
    "Healer's fee – Pay ₡50",
    "From sale of stolen goods you get ₡45.",
    "Get Out of Detention Free Card",
    "Go to Detention Block – Go directly to Detention Block – Do not pass START, do not collect ₡200",
    "Rebel Fund matures. Receive ₡100.",
    "Tax refund – Collect ₡20",
    "It is your birth-cycle. Collect ₡10 from each player.",
    "Life insurance matures – Collect ₡100",
    "Pay medical bay ₡100",
    "Pay training fees of ₡50",
    "Receive ₡25 bounty fee",
    "You are assessed for orbital repairs – Pay ₡40 per Dwelling, ₡115 per Fortress",
    "You have won second prize in a beauty contest – Collect ₡10",
    "Inherit ₡100"
];